package net.antopfr.advancedweather.config;

import dev.isxander.yacl3.api.ConfigCategory;
import dev.isxander.yacl3.api.Option;
import dev.isxander.yacl3.api.OptionDescription;
import dev.isxander.yacl3.api.OptionGroup;
import dev.isxander.yacl3.api.YetAnotherConfigLib;
import dev.isxander.yacl3.api.controller.*;
import net.antopfr.advancedweather.client.gui.hud.WeatherHudOverlay;
import net.minecraft.client.gui.screens.Screen;
import net.minecraft.network.chat.Component;

import java.awt.*;
import java.util.function.Consumer;
import java.util.function.Supplier;

public class AWConfigScreen {
    public static Screen create(Screen parent) {
        return new AWConfigSelectScreen(parent);
    }

    // CLIENT
    public static Screen createClient(Screen parent) {
        AWClientConfig config = AWClientConfig.get();

        YetAnotherConfigLib.Builder builder = YetAnotherConfigLib.createBuilder()
                .title(Component.literal("Advanced Weather - Client Settings"))
                .save(config::save);

        // WEATHER HUD
        ConfigCategory weatherHud = ConfigCategory.createBuilder()
                .name(Component.literal("Weather HUD"))
                .option(Option.<Boolean>createBuilder()
                        .name(Component.literal("Enable Weather HUD"))
                        .description(OptionDescription.of(Component.literal("Show a small permanent weather indicator on screen")))
                        .binding(true, () -> config.enableWeatherHud, v -> config.enableWeatherHud = v)
                        .controller(BooleanControllerBuilder::create)
                        .build())
                .option(Option.<Boolean>createBuilder()
                        .name(Component.literal("Show Time"))
                        .description(OptionDescription.of(Component.literal("Show the in-game time below the weather name")))
                        .binding(true, () -> config.weatherHudShowTime, v -> config.weatherHudShowTime = v)
                        .controller(BooleanControllerBuilder::create)
                        .build())
                .option(Option.<WeatherHudOverlay.HudPosition>createBuilder()
                        .name(Component.literal("HUD Position"))
                        .binding(WeatherHudOverlay.HudPosition.TOP_RIGHT, () -> config.weatherHudPosition, v -> config.weatherHudPosition = v)
                        .controller(opt -> EnumControllerBuilder.create(opt)
                                .enumClass(WeatherHudOverlay.HudPosition.class))
                        .build())
                .build();

        // UNITS
        ConfigCategory units = ConfigCategory.createBuilder()
                .name(Component.literal("Units"))
                .option(Option.<Boolean>createBuilder()
                        .name(Component.literal("Use Fahrenheit Unit"))
                        .description(OptionDescription.of(Component.literal("Use the Fahrenheit (°F) unit instead of Celsius (°C)")))
                        .binding(true, () -> config.useFahrenheit, v -> config.useFahrenheit = v)
                        .controller(BooleanControllerBuilder::create)
                        .build())
                .option(Option.<Boolean>createBuilder()
                        .name(Component.literal("Use Miles per Hour Unit"))
                        .description(OptionDescription.of(Component.literal("Use the Miles per Hour (mph) unit instead of Kilometers per Hour (km/h)")))
                        .binding(true, () -> config.useMph, v -> config.useMph = v)
                        .controller(BooleanControllerBuilder::create)
                        .build())
                .build();

        // WIND LINES
        ConfigCategory windLines = ConfigCategory.createBuilder()
                .name(Component.literal("Wind Lines"))
                .option(bool("Wind Pushes Particles", "Drift every particle along the wind direction", true,
                        () -> config.windPushesParticles, v -> config.windPushesParticles = v))
                .option(Option.<Double>createBuilder()
                        .name(Component.literal("Wind Particle Strength"))
                        .binding(1.0, () -> config.windParticleStrength, v -> config.windParticleStrength = v)
                        .controller(opt -> DoubleFieldControllerBuilder.create(opt).min(0.0).max(5.0))
                        .build())
                .option(Option.<Boolean>createBuilder()
                        .name(Component.literal("Enable Wind Bursts"))
                        .description(OptionDescription.of(Component.literal("Enable wind bursts (if disabled, wind lines spawn continuously)")))
                        .binding(true, () -> config.windBurstEnabled, v -> config.windBurstEnabled = v)
                        .controller(BooleanControllerBuilder::create)
                        .build())
                .option(Option.<Integer>createBuilder()
                        .name(Component.literal("Max Simultaneous Wind Lines"))
                        .description(OptionDescription.of(Component.literal("Max simultaneous wind lines")))
                        .binding(80, () -> config.windLineMax, v -> config.windLineMax = v)
                        .controller(opt -> IntegerSliderControllerBuilder.create(opt).range(10, 300).step(1))
                        .build())
                .option(Option.<Double>createBuilder()
                        .name(Component.literal("Min Wind Line Speed"))
                        .binding(0.18, () -> config.windLineSpeedMin, v -> config.windLineSpeedMin = v)
                        .controller(DoubleFieldControllerBuilder::create)
                        .build())
                .option(Option.<Double>createBuilder()
                        .name(Component.literal("Max Wind Line Speed"))
                        .binding(0.24, () -> config.windLineSpeedMax, v -> config.windLineSpeedMax = v)
                        .controller(DoubleFieldControllerBuilder::create)
                        .build())
                .option(Option.<Double>createBuilder()
                        .name(Component.literal("Min Wind Line Length"))
                        .binding(1.5, () -> config.windLineLengthMin, v -> config.windLineLengthMin = v)
                        .controller(DoubleFieldControllerBuilder::create)
                        .build())
                .option(Option.<Double>createBuilder()
                        .name(Component.literal("Max Wind Line Length"))
                        .binding(4.5, () -> config.windLineLengthMax, v -> config.windLineLengthMax = v)
                        .controller(DoubleFieldControllerBuilder::create)
                        .build())
                .option(Option.<Double>createBuilder()
                        .name(Component.literal("Min Spawn Distance"))
                        .binding(15.0, () -> config.windLineSpawnDistMin, v -> config.windLineSpawnDistMin = v)
                        .controller(DoubleFieldControllerBuilder::create)
                        .build())
                .option(Option.<Double>createBuilder()
                        .name(Component.literal("Max Spawn Distance"))
                        .binding(25.0, () -> config.windLineSpawnDistMax, v -> config.windLineSpawnDistMax = v)
                        .controller(DoubleFieldControllerBuilder::create)
                        .build())
                .option(Option.<Double>createBuilder()
                        .name(Component.literal("Lateral Spread"))
                        .binding(35.0, () -> config.windLineLateralSpread, v -> config.windLineLateralSpread = v)
                        .controller(DoubleFieldControllerBuilder::create)
                        .build())
                .option(Option.<Double>createBuilder()
                        .name(Component.literal("Height Spread"))
                        .binding(9.0, () -> config.windLineHeightSpread, v -> config.windLineHeightSpread = v)
                        .controller(DoubleFieldControllerBuilder::create)
                        .build())
                .option(Option.<Integer>createBuilder()
                        .name(Component.literal("Min Cooldown Between Bursts (ticks)"))
                        .binding(60, () -> config.windBurstCooldownMin, v -> config.windBurstCooldownMin = v)
                        .controller(opt -> IntegerSliderControllerBuilder.create(opt).range(5, 600).step(1))
                        .build())
                .option(Option.<Integer>createBuilder()
                        .name(Component.literal("Max Cooldown Between Bursts (ticks)"))
                        .binding(120, () -> config.windBurstCooldownMax, v -> config.windBurstCooldownMax = v)
                        .controller(opt -> IntegerSliderControllerBuilder.create(opt).range(5, 600).step(1))
                        .build())
                .option(Option.<Integer>createBuilder()
                        .name(Component.literal("Min Burst Duration (ticks)"))
                        .binding(60, () -> config.windBurstCooldownMin, v -> config.windBurstCooldownMin = v)
                        .controller(opt -> IntegerSliderControllerBuilder.create(opt).range(5, 600).step(1))
                        .build())
                .option(Option.<Integer>createBuilder()
                        .name(Component.literal("Max Burst Duration (ticks)"))
                        .binding(120, () -> config.windBurstCooldownMax, v -> config.windBurstCooldownMax = v)
                        .controller(opt -> IntegerSliderControllerBuilder.create(opt).range(5, 600).step(1))
                        .build())
                .build();

        // BLIZZARD
        ConfigCategory blizzard = ConfigCategory.createBuilder()
                .name(Component.literal("Blizzard Particles"))
                .option(Option.<Integer>createBuilder()
                        .name(Component.literal("Particles Per Batch"))
                        .description(OptionDescription.of(Component.literal("Increasing too much this value can cause performance issues on low-end devices")))
                        .binding(48, () -> config.blizzardCount, v -> config.blizzardCount = v)
                        .controller(opt -> IntegerSliderControllerBuilder.create(opt).range(1, 200).step(1))
                        .build())
                .option(Option.<Integer>createBuilder()
                        .name(Component.literal("Spawn Interval (ticks)"))
                        .description(OptionDescription.of(Component.literal("Increasing too much this value can cause performance issues on low-end devices")))
                        .binding(2, () -> config.blizzardTickInterval, v -> config.blizzardTickInterval = v)
                        .controller(opt -> IntegerSliderControllerBuilder.create(opt).range(1, 40).step(1))
                        .build())
                .option(Option.<Double>createBuilder()
                        .name(Component.literal("Spawn Distance"))
                        .binding(8.0, () -> config.blizzardSpawnDist, v -> config.blizzardSpawnDist = v)
                        .controller(DoubleFieldControllerBuilder::create)
                        .build())
                .option(Option.<Double>createBuilder()
                        .name(Component.literal("Horizontal Spread"))
                        .binding(16.0, () -> config.blizzardSpread, v -> config.blizzardSpread = v)
                        .controller(DoubleFieldControllerBuilder::create)
                        .build())
                .option(Option.<Double>createBuilder()
                        .name(Component.literal("Vertical Spread"))
                        .binding(12.0, () -> config.blizzardHeightSpread, v -> config.blizzardHeightSpread = v)
                        .controller(DoubleFieldControllerBuilder::create)
                        .build())
                .option(Option.<Double>createBuilder()
                        .name(Component.literal("Wind Speed"))
                        .binding(0.5, () -> config.blizzardWindSpeed, v -> config.blizzardWindSpeed = v)
                        .controller(DoubleFieldControllerBuilder::create)
                        .build())
                .option(Option.<Double>createBuilder()
                        .name(Component.literal("Min Particle Size"))
                        .binding(0.14, () -> config.blizzardSizeMin, v -> config.blizzardSizeMin = v)
                        .controller(DoubleFieldControllerBuilder::create)
                        .build())
                .option(Option.<Double>createBuilder()
                        .name(Component.literal("Max Particle Size"))
                        .binding(0.25, () -> config.blizzardSizeMax, v -> config.blizzardSizeMax = v)
                        .controller(DoubleFieldControllerBuilder::create)
                        .build())
                .build();

        // SAND PARTICLES
        ConfigCategory sandParticles = ConfigCategory.createBuilder()
                .name(Component.literal("Sand Particles"))
                .option(Option.<Integer>createBuilder()
                        .name(Component.literal("Particles Per Batch"))
                        .description(OptionDescription.of(Component.literal("Increasing too much this value can cause performance issues on low-end devices")))
                        .binding(48, () -> config.sandCount, v -> config.sandCount = v)
                        .controller(opt -> IntegerSliderControllerBuilder.create(opt).range(1, 200).step(1))
                        .build())
                .option(Option.<Integer>createBuilder()
                        .name(Component.literal("Spawn Interval (ticks)"))
                        .description(OptionDescription.of(Component.literal("Increasing too much this value can cause performance issues on low-end devices")))
                        .binding(2, () -> config.sandTickInterval, v -> config.sandTickInterval = v)
                        .controller(opt -> IntegerSliderControllerBuilder.create(opt).range(1, 40).step(1))
                        .build())
                .option(Option.<Double>createBuilder()
                        .name(Component.literal("Spawn Distance"))
                        .binding(8.0, () -> config.sandSpawnDist, v -> config.sandSpawnDist = v)
                        .controller(DoubleFieldControllerBuilder::create)
                        .build())
                .option(Option.<Double>createBuilder()
                        .name(Component.literal("Horizontal Spread"))
                        .binding(16.0, () -> config.sandSpread, v -> config.sandSpread = v)
                        .controller(DoubleFieldControllerBuilder::create)
                        .build())
                .option(Option.<Double>createBuilder()
                        .name(Component.literal("Vertical Spread"))
                        .binding(8.0, () -> config.sandHeightSpread, v -> config.sandHeightSpread = v)
                        .controller(DoubleFieldControllerBuilder::create)
                        .build())
                .option(Option.<Double>createBuilder()
                        .name(Component.literal("Wind Speed"))
                        .binding(0.8, () -> config.sandWindSpeed, v -> config.sandWindSpeed = v)
                        .controller(DoubleFieldControllerBuilder::create)
                        .build())
                .option(Option.<Double>createBuilder()
                        .name(Component.literal("Min Particle Size"))
                        .binding(0.22, () -> config.sandSizeMin, v -> config.sandSizeMin = v)
                        .controller(DoubleFieldControllerBuilder::create)
                        .build())
                .option(Option.<Double>createBuilder()
                        .name(Component.literal("Max Particle Size"))
                        .binding(0.27, () -> config.sandSizeMax, v -> config.sandSizeMax = v)
                        .controller(DoubleFieldControllerBuilder::create)
                        .build())
                .build();

        // BRIMSTONE PARTICLES
        ConfigCategory brimstoneParticles = ConfigCategory.createBuilder()
                .name(Component.literal("Brimstone Particles"))
                .option(Option.<Integer>createBuilder()
                        .name(Component.literal("Particles Per Batch"))
                        .description(OptionDescription.of(Component.literal("Increasing too much this value can cause performance issues on low-end devices")))
                        .binding(48, () -> config.brimstoneCount, v -> config.brimstoneCount = v)
                        .controller(opt -> IntegerSliderControllerBuilder.create(opt).range(1, 200).step(1))
                        .build())
                .option(Option.<Integer>createBuilder()
                        .name(Component.literal("Spawn Interval (ticks)"))
                        .description(OptionDescription.of(Component.literal("Increasing too much this value can cause performance issues on low-end devices")))
                        .binding(2, () -> config.brimstoneTickInterval, v -> config.brimstoneTickInterval = v)
                        .controller(opt -> IntegerSliderControllerBuilder.create(opt).range(1, 40).step(1))
                        .build())
                .option(Option.<Double>createBuilder()
                        .name(Component.literal("Spawn Distance"))
                        .binding(8.0, () -> config.brimstoneSpawnDist, v -> config.brimstoneSpawnDist = v)
                        .controller(DoubleFieldControllerBuilder::create)
                        .build())
                .option(Option.<Double>createBuilder()
                        .name(Component.literal("Horizontal Spread"))
                        .binding(16.0, () -> config.brimstoneSpread, v -> config.brimstoneSpread = v)
                        .controller(DoubleFieldControllerBuilder::create)
                        .build())
                .option(Option.<Double>createBuilder()
                        .name(Component.literal("Vertical Spread"))
                        .binding(8.0, () -> config.brimstoneHeightSpread, v -> config.brimstoneHeightSpread = v)
                        .controller(DoubleFieldControllerBuilder::create)
                        .build())
                .option(Option.<Double>createBuilder()
                        .name(Component.literal("Wind Speed"))
                        .binding(0.8, () -> config.brimstoneWindSpeed, v -> config.brimstoneWindSpeed = v)
                        .controller(DoubleFieldControllerBuilder::create)
                        .build())
                .option(Option.<Double>createBuilder()
                        .name(Component.literal("Min Particle Size"))
                        .binding(0.22, () -> config.brimstoneSizeMin, v -> config.brimstoneSizeMin = v)
                        .controller(DoubleFieldControllerBuilder::create)
                        .build())
                .option(Option.<Double>createBuilder()
                        .name(Component.literal("Max Particle Size"))
                        .binding(0.27, () -> config.brimstoneSizeMax, v -> config.brimstoneSizeMax = v)
                        .controller(DoubleFieldControllerBuilder::create)
                        .build())
                .build();

        // FOG WISPS
        ConfigCategory fogWisps = ConfigCategory.createBuilder()
                .name(Component.literal("Fog Wisps"))
                .option(Option.<Integer>createBuilder()
                        .name(Component.literal("Wisps Per Batch"))
                        .description(OptionDescription.of(Component.literal("Increasing too much this value can cause performance issues on low-end devices")))
                        .binding(8, () -> config.fogWispCount, v -> config.fogWispCount = v)
                        .controller(opt -> IntegerSliderControllerBuilder.create(opt).range(1, 50).step(1))
                        .build())
                .option(Option.<Integer>createBuilder()
                        .name(Component.literal("Spawn Interval (ticks)"))
                        .description(OptionDescription.of(Component.literal("Increasing too much this value can cause performance issues on low-end devices")))
                        .binding(6, () -> config.fogWispTickInterval, v -> config.fogWispTickInterval = v)
                        .controller(opt -> IntegerSliderControllerBuilder.create(opt).range(1, 40).step(1))
                        .build())
                .option(Option.<Double>createBuilder()
                        .name(Component.literal("Horizontal Spread"))
                        .binding(24.0, () -> config.fogWispSpread, v -> config.fogWispSpread = v)
                        .controller(DoubleFieldControllerBuilder::create)
                        .build())
                .option(Option.<Double>createBuilder()
                        .name(Component.literal("Vertical Spread"))
                        .binding(6.0, () -> config.fogWispHeightSpread, v -> config.fogWispHeightSpread = v)
                        .controller(DoubleFieldControllerBuilder::create)
                        .build())
                .option(Option.<Double>createBuilder()
                        .name(Component.literal("Min Opacity"))
                        .binding(0.3, () -> config.fogWispAlphaMin, v -> config.fogWispAlphaMin = v)
                        .controller(DoubleFieldControllerBuilder::create)
                        .build())
                .option(Option.<Double>createBuilder()
                        .name(Component.literal("Max Opacity"))
                        .binding(0.4, () -> config.fogWispAlphaMax, v -> config.fogWispAlphaMax = v)
                        .controller(DoubleFieldControllerBuilder::create)
                        .build())
                .option(Option.<Double>createBuilder()
                        .name(Component.literal("Min Size"))
                        .binding(1.2, () -> config.fogWispSizeMin, v -> config.fogWispSizeMin = v)
                        .controller(DoubleFieldControllerBuilder::create)
                        .build())
                .option(Option.<Double>createBuilder()
                        .name(Component.literal("Max Size"))
                        .binding(2.2, () -> config.fogWispSizeMax, v -> config.fogWispSizeMax = v)
                        .controller(DoubleFieldControllerBuilder::create)
                        .build())
                .option(Option.<Integer>createBuilder()
                        .name(Component.literal("Min Lifetime (ticks)"))
                        .binding(200, () -> config.fogWispLifetimeMin, v -> config.fogWispLifetimeMin = v)
                        .controller(opt -> IntegerSliderControllerBuilder.create(opt).range(20, 1000).step(1))
                        .build())
                .option(Option.<Integer>createBuilder()
                        .name(Component.literal("Max Lifetime (ticks)"))
                        .binding(300, () -> config.fogWispLifetimeMax, v -> config.fogWispLifetimeMax = v)
                        .controller(opt -> IntegerSliderControllerBuilder.create(opt).range(20, 1000).step(1))
                        .build())
                .build();

        // GROUND FOG
        ConfigCategory groundFog = ConfigCategory.createBuilder()
                .name(Component.literal("Ground Fog"))
                .option(Option.<Integer>createBuilder()
                        .name(Component.literal("Clouds Per Batch"))
                        .description(OptionDescription.of(Component.literal("Increasing too much this value can cause performance issues on low-end devices")))
                        .binding(8, () -> config.groundFogCount, v -> config.groundFogCount = v)
                        .controller(opt -> IntegerSliderControllerBuilder.create(opt).range(1, 30).step(1))
                        .build())
                .option(Option.<Integer>createBuilder()
                        .name(Component.literal("Spawn Interval (ticks)"))
                        .description(OptionDescription.of(Component.literal("Increasing too much this value can cause performance issues on low-end devices")))
                        .binding(3, () -> config.groundFogTickInterval, v -> config.groundFogTickInterval = v)
                        .controller(opt -> IntegerSliderControllerBuilder.create(opt).range(1, 40).step(1))
                        .build())
                .option(Option.<Double>createBuilder()
                        .name(Component.literal("Horizontal Spread"))
                        .binding(24.0, () -> config.groundFogSpread, v -> config.groundFogSpread = v)
                        .controller(DoubleFieldControllerBuilder::create)
                        .build())
                .option(Option.<Double>createBuilder()
                        .name(Component.literal("Min Opacity"))
                        .binding(0.1, () -> config.groundFogAlphaMin, v -> config.groundFogAlphaMin = v)
                        .controller(DoubleFieldControllerBuilder::create)
                        .build())
                .option(Option.<Double>createBuilder()
                        .name(Component.literal("Max Opacity"))
                        .binding(0.35, () -> config.groundFogAlphaMax, v -> config.groundFogAlphaMax = v)
                        .controller(DoubleFieldControllerBuilder::create)
                        .build())
                .option(Option.<Double>createBuilder()
                        .name(Component.literal("Min Size"))
                        .binding(0.6, () -> config.groundFogSizeMin, v -> config.groundFogSizeMin = v)
                        .controller(DoubleFieldControllerBuilder::create)
                        .build())
                .option(Option.<Double>createBuilder()
                        .name(Component.literal("Max Size"))
                        .binding(1.7, () -> config.groundFogSizeMax, v -> config.groundFogSizeMax = v)
                        .controller(DoubleFieldControllerBuilder::create)
                        .build())
                .option(Option.<Double>createBuilder()
                        .name(Component.literal("Width-to-Height Ratio"))
                        .description(OptionDescription.of(Component.literal("Width-to-height ratio of cloud sprite")))
                        .binding(3.5, () -> config.groundFogWidthScale, v -> config.groundFogWidthScale = v)
                        .controller(DoubleFieldControllerBuilder::create)
                        .build())
                .option(Option.<Integer>createBuilder()
                        .name(Component.literal("Min Lifetime (ticks)"))
                        .binding(300, () -> config.groundFogLifetimeMin, v -> config.groundFogLifetimeMin = v)
                        .controller(opt -> IntegerSliderControllerBuilder.create(opt).range(20, 2000).step(1))
                        .build())
                .option(Option.<Integer>createBuilder()
                        .name(Component.literal("Max Lifetime (ticks)"))
                        .binding(500, () -> config.groundFogLifetimeMax, v -> config.groundFogLifetimeMax = v)
                        .controller(opt -> IntegerSliderControllerBuilder.create(opt).range(20, 2000).step(1))
                        .build())
                .build();

        // FOG DISTANCES
        ConfigCategory fogDistances = ConfigCategory.createBuilder()
                .name(Component.literal("Fog Distances"))
                .option(Option.<Double>createBuilder()
                        .name(Component.literal("Fog Near Plane"))
                        .binding(5.0, () -> config.fogNear, v -> config.fogNear = v)
                        .controller(DoubleFieldControllerBuilder::create)
                        .build())
                .option(Option.<Double>createBuilder()
                        .name(Component.literal("Fog Far Plane"))
                        .binding(25.0, () -> config.fogFar, v -> config.fogFar = v)
                        .controller(DoubleFieldControllerBuilder::create)
                        .build())
                .option(Option.<Double>createBuilder()
                        .name(Component.literal("Dense Fog Near Plane"))
                        .binding(1.0, () -> config.denseFogNear, v -> config.denseFogNear = v)
                        .controller(DoubleFieldControllerBuilder::create)
                        .build())
                .option(Option.<Double>createBuilder()
                        .name(Component.literal("Dense Fog Far Plane"))
                        .binding(8.0, () -> config.denseFogFar, v -> config.denseFogFar = v)
                        .controller(DoubleFieldControllerBuilder::create)
                        .build())
                .option(Option.<Double>createBuilder()
                        .name(Component.literal("Mist Fog Near Plane"))
                        .binding(20.0, () -> config.mistFogNear, v -> config.mistFogNear = v)
                        .controller(DoubleFieldControllerBuilder::create)
                        .build())
                .option(Option.<Double>createBuilder()
                        .name(Component.literal("Mist Fog Far Plane"))
                        .binding(60.0, () -> config.mistFogFar, v -> config.mistFogFar = v)
                        .controller(DoubleFieldControllerBuilder::create)
                        .build())
                .option(Option.<Double>createBuilder()
                        .name(Component.literal("Hail Fog Near Plane"))
                        .binding(15.0, () -> config.hailFogNear, v -> config.hailFogNear = v)
                        .controller(DoubleFieldControllerBuilder::create)
                        .build())
                .option(Option.<Double>createBuilder()
                        .name(Component.literal("Hail Fog Far Plane"))
                        .binding(45.0, () -> config.hailFogFar, v -> config.hailFogFar = v)
                        .controller(DoubleFieldControllerBuilder::create)
                        .build())
                .option(Option.<Double>createBuilder()
                        .name(Component.literal("Blizzard Fog Near Plane"))
                        .binding(5.0, () -> config.blizzardFogNear, v -> config.blizzardFogNear = v)
                        .controller(DoubleFieldControllerBuilder::create)
                        .build())
                .option(Option.<Double>createBuilder()
                        .name(Component.literal("Blizzard Fog Far Plane"))
                        .binding(25.0, () -> config.blizzardFogFar, v -> config.blizzardFogFar = v)
                        .controller(DoubleFieldControllerBuilder::create)
                        .build())
                .option(Option.<Double>createBuilder()
                        .name(Component.literal("Freezing Rain Fog Near Plane"))
                        .binding(10.0, () -> config.freezingRainFogNear, v -> config.freezingRainFogNear = v)
                        .controller(DoubleFieldControllerBuilder::create)
                        .build())
                .option(Option.<Double>createBuilder()
                        .name(Component.literal("Freezing Rain Fog Far Plane"))
                        .binding(60.0, () -> config.freezingRainFogFar, v -> config.freezingRainFogFar = v)
                        .controller(DoubleFieldControllerBuilder::create)
                        .build())
                .option(Option.<Double>createBuilder()
                        .name(Component.literal("Thunderstorm Fog Near Plane"))
                        .binding(15.0, () -> config.thunderstormFogNear, v -> config.thunderstormFogNear = v)
                        .controller(DoubleFieldControllerBuilder::create)
                        .build())
                .option(Option.<Double>createBuilder()
                        .name(Component.literal("Thunderstorm Fog Far Plane"))
                        .binding(80.0, () -> config.thunderstormFogFar, v -> config.thunderstormFogFar = v)
                        .controller(DoubleFieldControllerBuilder::create)
                        .build())
                .build();

        // FOG DEFAULT COLORS
        ConfigCategory fogColors = ConfigCategory.createBuilder()
                .name(Component.literal("Fog Colors"))
                .option(Option.<Color>createBuilder()
                        .name(Component.literal("Fog Color"))
                        .binding(new Color(0xBFBFBF),
                                () -> new Color(config.fogColor),
                                v -> config.fogColor = v.getRGB() & 0xFFFFFF)
                        .controller(ColorControllerBuilder::create)
                        .build())
                .option(Option.<Color>createBuilder()
                        .name(Component.literal("Dense Fog Color"))
                        .binding(new Color(0xA6A6AD),
                                () -> new Color(config.denseFogColor),
                                v -> config.denseFogColor = v.getRGB() & 0xFFFFFF)
                        .controller(ColorControllerBuilder::create)
                        .build())
                .option(Option.<Color>createBuilder()
                        .name(Component.literal("Overcast Fog Color"))
                        .binding(new Color(0xA6A6AD),
                                () -> new Color(config.overcastColor),
                                v -> config.overcastColor = v.getRGB() & 0xFFFFFF)
                        .controller(ColorControllerBuilder::create)
                        .build())
                .option(Option.<Color>createBuilder()
                        .name(Component.literal("Mist Fog Color"))
                        .binding(new Color(0xC8CDD0),
                                () -> new Color(config.mistColor),
                                v -> config.mistColor = v.getRGB() & 0xFFFFFF)
                        .controller(ColorControllerBuilder::create)
                        .build())
                .option(Option.<Color>createBuilder()
                        .name(Component.literal("Thunderstorm Fog Color"))
                        .binding(new Color(0x596173),
                                () -> new Color(config.thunderstormColor),
                                v -> config.thunderstormColor = v.getRGB() & 0xFFFFFF)
                        .controller(ColorControllerBuilder::create)
                        .build())
                .option(Option.<Color>createBuilder()
                        .name(Component.literal("Freezing Rain Fog Color"))
                        .binding(new Color(0xB3CCE6),
                                () -> new Color(config.freezingRainColor),
                                v -> config.freezingRainColor = v.getRGB() & 0xFFFFFF)
                        .controller(ColorControllerBuilder::create)
                        .build())
                .option(Option.<Color>createBuilder()
                        .name(Component.literal("Hail Fog Color"))
                        .binding(new Color(0xCECFAB),
                                () -> new Color(config.hailColor),
                                v -> config.hailColor = v.getRGB() & 0xFFFFFF)
                        .controller(ColorControllerBuilder::create)
                        .build())
                .option(Option.<Color>createBuilder()
                        .name(Component.literal("Blizzard Fog Color"))
                        .binding(new Color(0xE0E0E0),
                                () -> new Color(config.blizzardColor),
                                v -> config.blizzardColor = v.getRGB() & 0xFFFFFF)
                        .controller(ColorControllerBuilder::create)
                        .build())
                .option(Option.<Color>createBuilder()
                        .name(Component.literal("Sandstorm (Desert) Fog Color"))
                        .binding(new Color(0xD9B05C),
                                () -> new Color(config.sandstormColor),
                                v -> config.sandstormColor = v.getRGB() & 0xFFFFFF)
                        .controller(ColorControllerBuilder::create)
                        .build())
                .option(Option.<Color>createBuilder()
                        .name(Component.literal("Sandstorm (Badlands) Fog Color"))
                        .binding(new Color(0xC57234),
                                () -> new Color(config.sandstormBadlandsColor),
                                v -> config.sandstormBadlandsColor = v.getRGB() & 0xFFFFFF)
                        .controller(ColorControllerBuilder::create)
                        .build())
                .build();


        // CLIENT categories
        builder.category(weatherHud);
        builder.category(units);
        builder.category(windLines);
        builder.category(blizzard);
        builder.category(sandParticles);
        builder.category(brimstoneParticles);
        builder.category(fogWisps);
        builder.category(groundFog);
        builder.category(fogDistances);
        builder.category(fogColors);

        return builder.build().generateScreen(parent);
    }

    // COMMON
    public static Screen createCommon(Screen parent) {
        AWCommonConfig common = AWCommonConfig.get();

        YetAnotherConfigLib.Builder builder = YetAnotherConfigLib.createBuilder()
                .title(Component.literal("Advanced Weather - Common Settings"))
                .save(common::save);

        // WEATHER TYPES
        ConfigCategory weatherTypes = ConfigCategory.createBuilder()
                .name(Component.literal("Weather Types"))
                .group(OptionGroup.createBuilder()
                        .name(Component.literal("Overworld"))
                        .option(bool("Fog", null, true, () -> common.enableFog, v -> common.enableFog = v))
                        .option(bool("Dense Fog", null, true, () -> common.enableDenseFog, v -> common.enableDenseFog = v))
                        .option(bool("Mist", null, true, () -> common.enableMist, v -> common.enableMist = v))
                        .option(bool("Sandstorm", null, true, () -> common.enableSandstorm, v -> common.enableSandstorm = v))
                        .option(bool("Blizzard", null, true, () -> common.enableBlizzard, v -> common.enableBlizzard = v))
                        .option(bool("Freezing Rain", null, true, () -> common.enableFreezingRain, v -> common.enableFreezingRain = v))
                        .option(bool("Hail", null, true, () -> common.enableHail, v -> common.enableHail = v))
                        .option(bool("Thunderstorm", null, true, () -> common.enableThunderstorm, v -> common.enableThunderstorm = v))
                        .build())
                .group(OptionGroup.createBuilder()
                        .name(Component.literal("Nether"))
                        .option(bool("Nether Weather", "Master toggle for all Nether weather", true, () -> common.enableNetherWeather, v -> common.enableNetherWeather = v))
                        .option(bool("Ash Storm", null, true, () -> common.enableAshStorm, v -> common.enableAshStorm = v))
                        .option(bool("Brimstone Storm", null, true, () -> common.enableBrimstoneStorm, v -> common.enableBrimstoneStorm = v))
                        .option(bool("Lava Rain", null, true, () -> common.enableLavaRain, v -> common.enableLavaRain = v))
                        .option(bool("Netherstorm", null, true, () -> common.enableNetherstorm, v -> common.enableNetherstorm = v))
                        .option(bool("Hellfire", null, true, () -> common.enableHellfire, v -> common.enableHellfire = v))
                        .build())
                .group(OptionGroup.createBuilder()
                        .name(Component.literal("The End"))
                        .option(bool("End Weather", "Master toggle for all End weather", true, () -> common.enableEndWeather, v -> common.enableEndWeather = v))
                        .option(bool("Void Storm", null, true, () -> common.enableVoidStorm, v -> common.enableVoidStorm = v))
                        .option(bool("End Mist", null, true, () -> common.enableEndMist, v -> common.enableEndMist = v))
                        .option(bool("Chorus Gale", null, true, () -> common.enableChorusGale, v -> common.enableChorusGale = v))
                        .option(bool("Enderstorm", null, true, () -> common.enableEnderstorm, v -> common.enableEnderstorm = v))
                        .build())
                .build();

        // GAMEPLAY
        ConfigCategory gameplay = ConfigCategory.createBuilder()
                .name(Component.literal("Gameplay"))
                .option(bool("Hail Damages Crops", null, true, () -> common.hailDamageCrops, v -> common.hailDamageCrops = v))
                .option(bool("Hail Damages Entities", null, true, () -> common.hailDamageEntities, v -> common.hailDamageEntities = v))
                .option(bool("Hail Breaks Glass", null, true, () -> common.hailBreakGlass, v -> common.hailBreakGlass = v))
                .option(bool("Heavy Rain Slows Crops", null, true, () -> common.heavyRainSlowCrops, v -> common.heavyRainSlowCrops = v))
                .option(bool("Rain Boosts Crops", "Drizzle and light rain speed up nearby crop growth", true, () -> common.rainBoostsCrops, v -> common.rainBoostsCrops = v))
                .option(bool("Frost Kills Crops", "Sustained blizzard or freezing rain destroys sky-exposed crops", true, () -> common.frostKillsCrops, v -> common.frostKillsCrops = v))
                .option(bool("Drought Dries Farmland", "Long, hot clear spells dry out exposed farmland", true, () -> common.droughtDriesFarmland, v -> common.droughtDriesFarmland = v))
                .option(bool("Wind Spreads Fire", "Strong wind carries fire one block downwind", true, () -> common.windSpreadsFire, v -> common.windSpreadsFire = v))
                .option(bool("Sandstorm Affects Players", "Slowness and hunger when exposed in a sandstorm", true, () -> common.sandstormAffectsPlayers, v -> common.sandstormAffectsPlayers = v))
                .option(bool("Station Requires Sensors", "Weather stations only show a reading when a matching sensor is linked", true, () -> common.stationRequiresSensors, v -> common.stationRequiresSensors = v))
                .option(Option.<Double>createBuilder()
                        .name(Component.literal("Sensor Link Max Distance"))
                        .description(OptionDescription.of(Component.literal("Maximum distance (blocks) between a sensor and its station")))
                        .binding(32.0, () -> common.sensorLinkMaxDistance, v -> common.sensorLinkMaxDistance = v)
                        .controller(opt -> DoubleFieldControllerBuilder.create(opt).min(1.0).max(256.0))
                        .build())
                .build();

        // REAL WEATHER
        ConfigCategory realWeather = ConfigCategory.createBuilder()
                .name(Component.literal("Real Weather"))
                .option(bool("Enable Real World Weather",
                        "Fetches live weather for the coordinates below from Open-Meteo, and the place name from OpenStreetMap Nominatim. These coordinates are sent to those services. Disabled by default.",
                        false, () -> common.realWeatherEnabled, v -> common.realWeatherEnabled = v))
                .option(Option.<Double>createBuilder()
                        .name(Component.literal("Latitude"))
                        .binding(48.8566, () -> common.latitude, v -> common.latitude = v)
                        .controller(opt -> DoubleFieldControllerBuilder.create(opt).min(-90.0).max(90.0))
                        .build())
                .option(Option.<Double>createBuilder()
                        .name(Component.literal("Longitude"))
                        .binding(2.3522, () -> common.longitude, v -> common.longitude = v)
                        .controller(opt -> DoubleFieldControllerBuilder.create(opt).min(-180.0).max(180.0))
                        .build())
                .option(Option.<Integer>createBuilder()
                        .name(Component.literal("Sync Interval (minutes)"))
                        .binding(4, () -> common.syncIntervalMinutes, v -> common.syncIntervalMinutes = v)
                        .controller(opt -> IntegerSliderControllerBuilder.create(opt).range(1, 120).step(1))
                        .build())
                .option(bool("Real Weather Overrides Commands", "Let fetched real weather override weather set via commands", false,
                        () -> common.realWeatherOverridesCommands, v -> common.realWeatherOverridesCommands = v))
                .build();

        // REPORTS & ARCHIVE
        ConfigCategory archive = ConfigCategory.createBuilder()
                .name(Component.literal("Reports & Archive"))
                .option(bool("Enable Weather Reports", null, true, () -> common.enableWeatherReports, v -> common.enableWeatherReports = v))
                .option(bool("Reject Older Reports", "Archives refuse reports older than their stored history", true, () -> common.archiveRejectOlderReports, v -> common.archiveRejectOlderReports = v))
                .option(Option.<Integer>createBuilder()
                        .name(Component.literal("Archive Max Records"))
                        .binding(20000, () -> common.archiveMaxRecords, v -> common.archiveMaxRecords = v)
                        .controller(opt -> IntegerFieldControllerBuilder.create(opt).min(1))
                        .build())
                .option(Option.<Integer>createBuilder()
                        .name(Component.literal("Min Records For Forecast"))
                        .binding(15, () -> common.archiveMinRecordsForForecast, v -> common.archiveMinRecordsForForecast = v)
                        .controller(opt -> IntegerFieldControllerBuilder.create(opt).min(0))
                        .build())
                .option(Option.<Integer>createBuilder()
                        .name(Component.literal("Confidence Floor Records"))
                        .binding(15, () -> common.archiveConfidenceFloorRecords, v -> common.archiveConfidenceFloorRecords = v)
                        .controller(opt -> IntegerFieldControllerBuilder.create(opt).min(0))
                        .build())
                .option(Option.<Integer>createBuilder()
                        .name(Component.literal("Confidence Saturation Records"))
                        .binding(200, () -> common.archiveConfidenceSaturationRecords, v -> common.archiveConfidenceSaturationRecords = v)
                        .controller(opt -> IntegerFieldControllerBuilder.create(opt).min(1))
                        .build())
                .option(Option.<Integer>createBuilder()
                        .name(Component.literal("Almanac Max Records"))
                        .binding(32, () -> common.almanacMaxRecords, v -> common.almanacMaxRecords = v)
                        .controller(opt -> IntegerFieldControllerBuilder.create(opt).min(1))
                        .build())
                .option(Option.<Integer>createBuilder()
                        .name(Component.literal("Report Printing Time (ticks)"))
                        .binding(30, () -> common.reportPrintingTicks, v -> common.reportPrintingTicks = v)
                        .controller(opt -> IntegerSliderControllerBuilder.create(opt).range(1, 200).step(1))
                        .build())
                .option(Option.<Long>createBuilder()
                        .name(Component.literal("Forecast Horizon (ticks)"))
                        .binding(1200L, () -> common.archiveForecastHorizonTicks, v -> common.archiveForecastHorizonTicks = v)
                        .controller(LongFieldControllerBuilder::create)
                        .build())
                .option(Option.<Long>createBuilder()
                        .name(Component.literal("Aging Data Threshold (ticks)"))
                        .binding(12000L, () -> common.archiveAgingDataTicks, v -> common.archiveAgingDataTicks = v)
                        .controller(LongFieldControllerBuilder::create)
                        .build())
                .option(Option.<Long>createBuilder()
                        .name(Component.literal("Outdated Data Threshold (ticks)"))
                        .binding(24000L, () -> common.archiveOutdatedDataTicks, v -> common.archiveOutdatedDataTicks = v)
                        .controller(LongFieldControllerBuilder::create)
                        .build())
                .build();

        // CREATE COMPAT
        ConfigCategory createCompat = ConfigCategory.createBuilder()
                .name(Component.literal("Create Compatibility"))
                .option(bool("Enable Windmill Compat", null, true, () -> common.enableCreateWindmillCompat, v -> common.enableCreateWindmillCompat = v))
                .option(bool("Wind Direction Affects Output", null, true, () -> common.windmillDirectionAffectsOutput, v -> common.windmillDirectionAffectsOutput = v))
                .option(Option.<Double>createBuilder()
                        .name(Component.literal("Windmill Wind Threshold"))
                        .binding(0.4, () -> common.windmillWindThreshold, v -> common.windmillWindThreshold = v)
                        .controller(opt -> DoubleFieldControllerBuilder.create(opt).min(0.0).max(1.0))
                        .build())
                .option(Option.<Double>createBuilder()
                        .name(Component.literal("Windmill Speed Scale Factor"))
                        .binding(0.3, () -> common.windmillSpeedScaleFactor, v -> common.windmillSpeedScaleFactor = v)
                        .controller(opt -> DoubleFieldControllerBuilder.create(opt).min(0.0).max(5.0))
                        .build())
                .build();

        builder.category(weatherTypes);
        builder.category(gameplay);
        builder.category(realWeather);
        builder.category(archive);
        builder.category(createCompat);

        return builder.build().generateScreen(parent);
    }

    private static Option<Boolean> bool(String name, String desc, boolean def, Supplier<Boolean> getter, Consumer<Boolean> setter) {
        Option.Builder<Boolean> b = Option.<Boolean>createBuilder()
                .name(Component.literal(name));
        if (desc != null) {
            b.description(OptionDescription.of(Component.literal(desc)));
        }
        return b.binding(def, getter, setter)
                .controller(BooleanControllerBuilder::create)
                .build();
    }
}
